// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTvgkH0vRO-Ij5u10hh4jCvhCZ4-LhIFM',
    appId: '1:1098283124220:web:d1447dcb1f977fcc0ade79',
    messagingSenderId: '1098283124220',
    projectId: 'unite-a-gamer',
    authDomain: 'unite-a-gamer.firebaseapp.com',
    storageBucket: 'unite-a-gamer.firebasestorage.app',
    measurementId: 'G-9GJ2NSDB19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSporok5Hd9xnHltZz2h6e6_LsKfn6RI8',
    appId: '1:1098283124220:android:046c8bdc5d51a3410ade79',
    messagingSenderId: '1098283124220',
    projectId: 'unite-a-gamer',
    storageBucket: 'unite-a-gamer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwbgINd97iuaDkdIu3BTa5et2vNCDMyNk',
    appId: '1:1098283124220:ios:254ddd5bf3e1bc2b0ade79',
    messagingSenderId: '1098283124220',
    projectId: 'unite-a-gamer',
    storageBucket: 'unite-a-gamer.firebasestorage.app',
    iosClientId:
        '1098283124220-jh6k4bgmjfngsqh6ab48cc08jb7gdg5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniteAGamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwbgINd97iuaDkdIu3BTa5et2vNCDMyNk',
    appId: '1:1098283124220:ios:254ddd5bf3e1bc2b0ade79',
    messagingSenderId: '1098283124220',
    projectId: 'unite-a-gamer',
    storageBucket: 'unite-a-gamer.firebasestorage.app',
    iosClientId:
        '1098283124220-jh6k4bgmjfngsqh6ab48cc08jb7gdg5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniteAGamer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTvgkH0vRO-Ij5u10hh4jCvhCZ4-LhIFM',
    appId: '1:1098283124220:web:60ba32febdf866f50ade79',
    messagingSenderId: '1098283124220',
    projectId: 'unite-a-gamer',
    authDomain: 'unite-a-gamer.firebaseapp.com',
    storageBucket: 'unite-a-gamer.firebasestorage.app',
    measurementId: 'G-65FY7WTKT6',
  );
}
