import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:uuid/uuid.dart';
import 'package:uag_traders_hub/features/trading_hub/arc_raiders/session_planner/session_model.dart';

class UagSessionRepository {
  UagSessionRepository({FirebaseFirestore? firestore, FirebaseAuth? auth}) : _firestore = firestore ?? FirebaseFirestore.instance, _auth = auth ?? FirebaseAuth.instance;
  final FirebaseFirestore _firestore; final FirebaseAuth _auth; static const String collectionPath = 'uag_sessions';
  CollectionReference<Map<String, dynamic>> get _sessions => _firestore.collection(collectionPath);
  String get currentUid { final uid = _auth.currentUser?.uid; if (uid == null) throw StateError('User must be signed in.'); return uid; }
  Future<String> createManualSession({required String type, required String participantTwoUid, required String participantTwoDisplayName, required String participantTwoEmbarkId, required DateTime scheduledAt, required String timezone, required String notes}) async { final user = _auth.currentUser; if (user == null) throw StateError('User must be signed in.'); final id = const Uuid().v4(); final session = UagSession(id: id, type: type, game: 'arc_raiders', createdBy: user.uid, participantOneUid: user.uid, participantTwoUid: participantTwoUid, participantOneDisplayName: user.displayName ?? user.email ?? 'You', participantTwoDisplayName: participantTwoDisplayName, participantOneEmbarkId: '', participantTwoEmbarkId: participantTwoEmbarkId, scheduledAt: scheduledAt, timezone: timezone, status: 'scheduled', notes: notes); final data = session.toMap(); data['createdAt'] = FieldValue.serverTimestamp(); await _sessions.doc(id).set(data); return id; }
  Stream<List<UagSession>> streamMySessions() { final uid = currentUid; final controller = StreamController<List<UagSession>>(); List<UagSession> one = <UagSession>[]; List<UagSession> two = <UagSession>[]; void emit() { final merged = <String, UagSession>{}; for (final session in [...one, ...two]) { merged[session.id] = session; } final sessions = merged.values.toList()..sort((a, b) => a.scheduledAt.compareTo(b.scheduledAt)); if (!controller.isClosed) controller.add(sessions); } final subOne = _sessions.where('participantOneUid', isEqualTo: uid).orderBy('scheduledAt').snapshots().listen((snapshot) { one = snapshot.docs.map(UagSession.fromDoc).toList(growable: false); emit(); }, onError: controller.addError); final subTwo = _sessions.where('participantTwoUid', isEqualTo: uid).orderBy('scheduledAt').snapshots().listen((snapshot) { two = snapshot.docs.map(UagSession.fromDoc).toList(growable: false); emit(); }, onError: controller.addError); controller.onCancel = () async { await subOne.cancel(); await subTwo.cancel(); }; return controller.stream; }
  Future<void> updateStatus(String id, String status) => _sessions.doc(id).update(<String, dynamic>{'status': status, 'updatedAt': FieldValue.serverTimestamp()});
  Future<void> toggleReady(UagSession session) { final uid = currentUid; final field = uid == session.participantOneUid ? 'participantOneReady' : 'participantTwoReady'; final current = uid == session.participantOneUid ? session.participantOneReady : session.participantTwoReady; return _sessions.doc(session.id).update(<String, dynamic>{field: !current, 'updatedAt': FieldValue.serverTimestamp()}); }
  Future<void> markComplete(UagSession session) { final uid = currentUid; final field = uid == session.participantOneUid ? 'participantOneCompleted' : 'participantTwoCompleted'; return _sessions.doc(session.id).update(<String, dynamic>{field: true, 'status': 'completed', 'updatedAt': FieldValue.serverTimestamp()}); }
  Future<void> markNoShow(UagSession session) { final uid = currentUid; final field = uid == session.participantOneUid ? 'participantTwoNoShow' : 'participantOneNoShow'; return _sessions.doc(session.id).update(<String, dynamic>{field: true, 'status': 'no_show', 'updatedAt': FieldValue.serverTimestamp()}); }
}
